services:
  leader:
    image: key-val-store:0.0.1
    ports:
      - 8080:8080
    environment:
      - followers=follower1:8080,follower2:8080
  
  follower1:
    image: key-val-store:0.0.1
    ports:
      - 8081:8080
  
  follower2:
    image: key-val-store:0.0.1
    ports:
      - 8082:8080