services:
  node1:
    image: key-val-store:0.0.1
    ports:
      - 8080:8080
    environment:
      - ID=1
    depends_on:
      - config
  
  node2:
    image: key-val-store:0.0.1
    ports:
      - 8081:8080
    environment:
      - ID=2
    depends_on:
      - config
  
  node3:
    image: key-val-store:0.0.1
    ports:
      - 8082:8080
    environment:
      - ID=3
    depends_on:
      - config

  config:
    image: key-val-store:0.0.1
    ports:
      - 8083:8080
    environment:
      - ID=0