services:
  node1:
    image: key-val-store:0.0.1
    ports:
      - 8080:8080
    environment:
      - followers=node2:8080,node3:8080
  
  node2:
    image: key-val-store:0.0.1
    ports:
      - 8081:8080
  
  node3:
    image: key-val-store:0.0.1
    ports:
      - 8082:8080